import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src="/logo.png"
          alt="LogSpi Logo"
          className={styles.vercelLogo}
          width={600}
          height={255}
          priority
        />
        <div className={styles.center}>
         <h1 >we're coming soon</h1>
         <hr />
        </div>
        We're coming soon! We're working hard to give you the best experience!
      </main>
    </>
  )
}
